# Base configs
baseurl: ""
url: "http://mattbiggin.co.uk"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-10211562-7"

# UI configs
title: "by Matt Biggin"
subtitle: "Documentary and Stret Photography"
author: "Matt Biggin"
bio: "Documentary and Street Photography"
web_design: "AJ"
social_urls:
  twitter: "https://twitter.mattbiggin.co.uk"
  instagram: "https://instagram.mattbiggin.co.uk"
  linkedin: "https://linkedin.mattbiggin.co.uk"
  github: "https://github.mattbiggin.co.uk"
  

theme: jekyll-theme-slate
